name: Build Package Screen Builder
on:
  pull_request:
    types: [opened, reopened, synchronize, edited, closed]
  schedule:
    - cron: '45 02 * * *'
  workflow_dispatch:  
jobs:
  run_deploy:
    name: Run Build PM4-workflow
    uses: processmaker/processmaker/.github/workflows/deploy-pm4.yml@next
    secrets: inherit
