name: npm pack

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: npm-pack-${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pack:
    uses: ProcessMaker/.github/.github/workflows/js-pack.yml@js-builds-2
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
